---
- name: Полный деплой интернет-магазина и мониторинга в Kubernetes
  hosts: boutique_server
  become: true
  tasks:
    - name: 1. Убеждаемся, что Docker установлен и запущен
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: 4. Создаем целевую директорию для приложения на ноутбуке
      ansible.builtin.file:
        path: /home/qadmin/microservices-demo
        state: directory
        owner: qadmin
        group: qadmin
        mode: '0755'

    - name: 5. Копируем все манифесты Kubernetes на ноутбук
      ansible.builtin.copy:
        src: ./kubernetes-manifests/
        dest: /home/qadmin/microservices-demo/kubernetes-manifests/
        owner: qadmin
        group: qadmin
        mode: '0755'

    - name: 6. Деплоим манифесты в Kubernetes (Minikube)
      ansible.builtin.command: /snap/bin/kubectl apply -f /home/qadmin/microservices-demo/kubernetes-manifests/ --validate=false
      environment:
        KUBECONFIG: /home/qadmin/.kube/config # <-- ЯВНО УКАЗЫВАЕМ ПУТЬ К КЛАСТЕРУ
      become: false # Выполняем от пользователя qadmin
      ignore_errors: true
      changed_when: true
