name: Проверка Ansible Плейбука

on:
  push:
    branches: [ main ]

jobs:
  check-code:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: 1. Скачиваем наш код из репозитория
        uses: actions/checkout@v4

      - name: 2. Запускаем официальный линтер Ansible
        uses: ansible-actions/ansible-lint-action@v1.0.3
        with:
          target: deploy.yml
