name: Проверка Ansible Плейбука

on:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Скачиваем наш код из репозитория
      uses: actions/checkout@v4

    - name: 2. Запускаем линтер для проверки ошибок в Ansible
      uses: ansible/ansible-lint-action@main
